kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  annotations:
    # indicate that this is provisioned dynamically, so the system works properly
    pv.kubernetes.io/provisioned-by: net.packet.csi
spec:
  # make sure the storage class is one that is from the setup
  storageClassName: csi-packet-performance
  # by default, the volume will be not deleted if you delete the PVC, change to
  # "Delete" if you wish the volume to be deleted automatically with the PVC
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: net.packet.csi
    fsType: ext4
    # You will have to add your Packet block storage volume ID for the volumeHandle
    #  since a PersistentVolume works with _already_ provisioned storage (static)
    #  and not automatically created (dynamic). If you want dynamic, use a
    #  PersistentVolumeClaim (pvc), for example, see demo-pod.yaml
    volumeHandle: BLOCK_VOLUME_ID
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1572974631219-8081-net.packet.csi

