kind: Service
apiVersion: v1
metadata:
  name: csi-packet-pd
  labels:
    app: csi-packet-pd
spec:
  selector:
    app: csi-packet-pd
  ports:
    - name: dummy
      port: 12345

---

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-packet-controller
spec:
  updateStrategy: 
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  serviceName: "csi-packet-pd"
  replicas: 1
  selector:
    matchLabels:
      app: csi-packet-pd-driver
  template:
    metadata:
      labels:
        app: csi-packet-pd-driver
    spec:
      serviceAccount: csi-controller-sa
      containers:
        - name: csi-external-provisioner
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-provisioner:v0.2.0
          args:
            - "--v=5"
            - "--provisioner=csi-packet"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-attacher:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: packet-driver
          imagePullPolicy: Always
          image: gcr.io/stackpoint-public/csi-packet-driver:0.0.2
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--config=/etc/cloud-sa/cloud-sa.json"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: cloud-sa-volume
              readOnly: true
              mountPath: "/etc/cloud-sa"
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: cloud-sa-volume
          secret:
            secretName: cloud-sa
